export const wordLists = {
  '2min200words': [
    "le", "de", "un", "à", "être", "et", "en", "avoir", "que", "pour", "dans", "ce", "il", "qui",
    "ne", "sur", "se", "pas", "plus", "pouvoir", "par", "je", "avec", "tout", "faire", "son",
    "mettre", "autre", "on", "mais", "nous", "comme", "ou", "si", "leur", "y", "dire", "elle",
    "devoir", "avant", "deux", "même", "prendre", "où", "aussi", "celui", "donner", "bien",
    "fois", "vous", "encore", "nouveau", "aller", "cela", "entre", "premier", "vouloir", "déjà",
    "grand", "mon", "me", "moins", "aucun", "lui", "temps", "très", "savoir", "falloir", "voir",
    "quelque", "sans", "raison", "notre", "dont", "non", "an", "monde", "jour", "monsieur",
    "demander", "alors", "après", "trouver", "personne", "rendre", "part", "dernier", "venir",
    "pendant", "passer", "peu", "lequel", "suite", "bon", "comprendre", "depuis", "point",
    "ainsi", "heure", "rester", "quel", "votre", "chaque", "rien", "pendant", "seulement",
    "devenir", "penser", "suivre", "croire", "reprendre", "montrer", "parler", "laisser",
    "quelques", "plusieurs", "aujourd'hui", "jamais", "souvent", "parfois", "toujours", "vraiment",
    "pourtant", "enfin", "ainsi", "tel", "tellement", "assez", "mieux", "moyen", "endroit",
    "autre", "chose", "nuit", "femme", "homme", "vie", "enfant", "oeil", "coeur", "main", "bras",
    "corps", "terre", "soleil", "ciel", "mer", "eau", "feu", "air", "ville", "rue", "route",
    "maison", "porte", "chambre", "table", "lit", "papier", "livre", "histoire", "mot", "idée",
    "sens", "force", "paix", "guerre", "état", "droit", "ordre", "politique", "pays", "peuple",
    "société", "famille", "travail", "argent", "école", "professeur", "élève", "classe", "leçon",
    "devoir", "examen", "succès", "échec", "jeu", "amusant", "facile", "difficile", "rapide",
    "lent", "fort", "faible", "jeune", "vieux", "petit", "grand", "beau", "joli", "noir", "blanc",
    "rouge", "bleu", "vert", "jaune", "orange", "brun", "gris", "rose", "mauve", "calme", "libre",
    "clair", "sombre", "triste", "joyeux", "heureux", "malheureux"
  ],
  '2minHARDchara': [
    "déjà", "où", "là", "étudiant", "garçon", "français", "façade", "Noël", "Noël", "Noël",
    "château", "forêt", "fenêtre", "connaître", "maître", "plutôt", "aussitôt", "paraître",
    "naître", "île", "cœur", "œuvre", "sœur", "manœuvre", "maçon", "glaçon", "leçon", "façon",
    "provençal", "aperçu", "conçu", "déçu", "reçu", "bientôt", "théâtre", "évènement", "crème",
    "pêche", "pêcheur", "goût", "brûler", "sûr", "mûr", "évêque", "fête", "tête", "rêve",
    "bête", "intérêt", "prêt", "fenêtre", "arrêt", "forêt", "grâce", "lâcher", "hâte", "pâte",
    "gâteau", "râteau", "plateau", "chapeau", "cadeau", "oiseau", "couteau", "bateau", "manteau",
    "anneau", "tonneau", "morceau", "pinceau", "rideau", "bureau", "niveau", "roseau", "fuseau",
    "ciseau", "tableau", "taureau", "corbeau", "agneau", "poireau", "chameau", "traîneau",
    "vaisseau", "cerveau", "aveugle", "enchaîner", "déchaîner", "traîner", "connaître",
    "maître", "maîtresse", "naître", "renaître", "paraître", "comparaître", "disparaître",
    "reconnaître", "apparaître", "croître", "accroître", "décroître", "recroître", "boîte",
    "cloître", "benoît", "chaîne", "déchaîner", "traîner", "entraîner", "glaïeul", "naïf",
    "naïve", "maïs", "laïc", "haïr", "haïssable", "théière", "païen", "coïncidence", "héroïne",
    "laïcité", "ambiguïté", "contiguïté", "exiguïté", "inouï", "inouïe", "ouï-dire", "ouïe",
    "trottiner", "chaînon", "faîtage", "faîtière", "traînée", "traîneau", "traîneur", "maîtrise",
    "plaît", "naît", "paraît", "connaît", "disparaît", "reconnaît", "apparaît", "accroît",
    "décroît", "coût", "coûter", "goût", "goûter", "goûteur", "voûte", "voûter", "août",
    "aoûtien", "croûte", "croûton", "mûr", "mûre", "mûrement", "sûr", "sûre", "sûrement",
    "dû", "dûment", "crû", "recrû", "affût", "affûter", "brûler", "flûte", "piqûre", "boîtier",
    "boîteux", "clôture", "clôturer", "huître", "huîtrier", "rafraîchir", "fraîcheur", "chaînage",
    "entraîneur", "renaît", "accroît", "brûlage", "brûlure", "fût", "fût-il", "pût", "fût"
  ]
};
